## https://raw.githubusercontent.com/xiaolin8/KubernetesInAction/master/pod_affinity.yaml
apiVersion: v1
kind: Service
metadata:
  name: kubia2
spec:
  sessionAffinity: ClientIP
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: kubia